### ISSUE TITLE
サンキュー画面にてエラーが表示されました

### ISSUE THREAD

**Issue by k-takasu** [movabletype/mt-plugin-notifylist#1]
プラグインをダウンロード・インストールを行い、フォームを作成し、使用してみたところ
サンキュー画面にてエラーが表示されました。
*登録メールの受信、及び受信したメールからのMTアドレス帳登録は正常に動作致しました。

ローカライズ機能で_NOTIFY_REQUIRE_CONFIRMATIONが読み込みに失敗しているためだと思うのですが。どのように修正すればよいかわかりませんでした。
プラグインの不具合は修正できますでしょうか。

**Comment by masiuchi** [comment]
ご報告ありがとうございます。
こちら修正しますので、しばらくお待ちください。

**Comment by masiuchi** [comment]
@k-takasu 修正しました。ご確認いただけますと幸いです。

**Comment by k-takasu** [comment]
正常に動作しました、ありがとうございます！

**Comment by masiuchi** [comment]
ご確認ありがとうございました！
